---
mongodb_exporter_version: "0.43.1"
mongodb_exporter_arch: amd64
mongodb_exporter_user: mongodb_exporter
mongodb_exporter_bin: /usr/local/bin/mongodb_exporter
mongodb_exporter_service_name: mongodb_exporter
mongodb_exporter_port: 9216

mongodb_exporter_db_user: mongodb_exporter
mongodb_exporter_db_password: "{{ vault_mongodb_exporter_password }}"
mongodb_exporter_db_host: 127.0.0.1
mongodb_exporter_db_port: 27017
mongodb_exporter_uri: "mongodb://{{ mongodb_exporter_db_user }}:{{ mongodb_exporter_db_password }}@{{ mongodb_exporter_db_host }}:{{ mongodb_exporter_db_port }}/admin"
