---
galaxy_info:
  author: NetFusion
  description: Install and configure Grafana Loki
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
dependencies: []

