---
postgres_exporter_version: "0.17.1"
postgres_exporter_port: 9187

postgres_exporter_user: postgres_exporter
postgres_exporter_bin: /usr/local/bin/postgres_exporter

postgres_exporter_data_source:
  user: postgres_exporter
  password: changeme
  host: 127.0.0.1
  port: 5432
  database: postgres
  sslmode: disable
